AllCops:
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 17

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/RescueStandardError:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
